### ISSUE TITLE
How do i deploy the demo..

### ISSUE THREAD

**Issue by mrpackethead** [aws-samples/aws-reinvent-2019-trivia-game#2]
Hi, thanks for an excellent session at reinvent.   A really useful set of info.

i was wondering if there was any more info on how to deploy this demo?

**Comment by clareliguori** [comment]
Each of the sub-directories have instructions on how to deploy the individual components.

For example:
Backend: https://github.com/aws-samples/aws-reinvent-2019-trivia-game/tree/master/trivia-backend
Frontend: https://github.com/aws-samples/aws-reinvent-2019-trivia-game/blob/master/static-site/README.md
