### ISSUE TITLE
Deploys using EXTERNAL deployment controller

### ISSUE THREAD

**Issue by rectalogic** [aws-samples/aws-reinvent-2019-trivia-game#244]
How are new versions of the backend deployed when using the CloudFormation infra for EXTERNAL deployment controller?
https://github.com/aws-samples/aws-reinvent-2019-trivia-game/tree/master/trivia-backend/infra/cfn-task-sets

Deploying EXTERNAL task sets are not discussed here https://github.com/aws-samples/aws-reinvent-2019-trivia-game/tree/master/trivia-backend

Would I use the CLI to create a new taskdefinition referencing the new image, and a new taskset `aws ecs register-task-definition` `aws ecs create-task-set` and then update the primary taskset `aws ecs update-service-primary-task-set`? But then CloudFormation will be out of sync and future stack updates may fail.

**Comment by clareliguori** [comment]
This is an example of letting CodeDeploy orchestrate the blue-green deployment of task sets with the EXTERNAL deployment controller. Every time the stack update has a change to the task definition image in the template, CodeDeploy will manage updating the task sets in the right order and keep the CloudFormation stack in sync.

https://github.com/aws-samples/aws-reinvent-2019-trivia-game/blob/master/trivia-backend/infra/codedeploy-blue-green-cfn/template.yaml

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/blue-green.html

**Comment by rectalogic** [comment]
> This is an example of letting CodeDeploy orchestrate the blue-green deployment of task sets with the EXTERNAL deployment controller. 
>
> https://github.com/aws-samples/aws-reinvent-2019-trivia-game/blob/master/trivia-backend/infra/codedeploy-blue-green-cfn/template.yaml

Yes, but I'm asking about https://github.com/aws-samples/aws-reinvent-2019-trivia-game/blob/master/trivia-backend/infra/cfn-task-sets/template.yaml not https://github.com/aws-samples/aws-reinvent-2019-trivia-game/blob/master/trivia-backend/infra/codedeploy-blue-green-cfn/template.yaml

**Comment by clareliguori** [comment]
That cfn-task-sets example was only meant as an example of how to provision task sets in CloudFormation, so I don't have an example of using it to deploy on an ongoing basis.  You have a few options depending on how you want to coordinate your deployments:
1. Use CloudFormation to only stand up the initial task sets, and then directly use ECS APIs to create new task sets moving forward, as you suggested.
2. Let CloudFormation create a new task set for you when your image changes.  Most attributes for the TaskSet resource type are "Requires replacement", including TaskDefinition: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskset.html.  So when a new version of the task definition is created in the template with a new image, CFN will go through its normal replacement logic for the task set: CFN will first create a new task set with the new task def, let it stabilize, update it to be the primary task set, then will drain and delete the old task set.  This would be a basic blue/green deployment without any traffic shifting.
3. If you need more advanced deployment coordination like traffic shifting between two target groups, you can either use CodeDeploy as I mentioned or you would need to generate multiple versions of the CFN template (one to create the new task set, one or more to do the traffic shifting, one to delete the old task set, etc) and then update the stack with each template sequentially.
