### ISSUE TITLE
Seeking some clarification on your article

### ISSUE THREAD

**Issue by mrpackethead** [aws-samples/aws-reinvent-2019-trivia-game#271]
Hi Clare, sorry that I've raised this as an issue in an unrelated repo, but i didn't know how to contact you otherwise..   And thanks for your sessions at Reinvent ( the stay at home version ).. Helpful stuff! and quite timely. 

I'm actively using cdk-pipelines which is still in experimental.. One of the topics that is being discussed is if a pipeline should only have a single source.    As coded right now, it only as one,  and i've found that to be quite restrictive.  

Your article ( https://aws.amazon.com/builders-library/automating-safe-hands-off-deployments/ ) is being used as a reference, to model it from ( see  https://github.com/aws/aws-cdk/issues/10872 )..  

I've re-read your article several times, and i cant' find anything to suggest that a pipeline can only have one source. The only suggestion in your article is that 'Source' has been shown as a single box in some of the diagrams. 

I have a use case where i don't' have much choice but to have multiple sources, because the ownership/business models precludes it all from being in a single source.     My IaC repo is in one place,  and the repos for a number of containers are owned by others in other places.      However, a commit in either place, needs to trigger some changes.     I'd love to have everything in one place, but it just wont' happen. 

I've hacked a solution together to get around it, by having my code build post stage kick of the cdk pipelines, after its finished building an image and placing it in ECR. 

```
  post_build:
    commands: |
      echo Build completed on $(date)
      echo Pushing the Docker image...
      docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      aws ssm put-parameter --name "/$INFRA_PIPELINE/$IMAGE_NAME/CurrentTag" --type "String" --value "$IMAGE_TAG" --overwrite
      aws codepipeline start-pipeline-execution --name $INFRA_PIPELINE
```

This feels like a 'hacky' hack. 

Is their any chance you could clarify if you article really meant that there should only be one source?

**Comment by clareliguori** [comment]
Commented on the CDK issue
