### ISSUE TITLE
Trigger for each of the delivery pipelines

### ISSUE THREAD

**Issue by alexpulver** [aws-samples/aws-reinvent-2019-trivia-game#300]
Hi,

First of all, it's a great project to learn from! Thanks for building it 😃.

Do I understand correctly that all pipelines will run on each commit? If so, wouldn't it be preferable (from time, cost and operations perspective) to have a separate Git repository for each component? That would include the pipeline, infrastructure and runtime. 

I understand that it is much easier to reason about the workload when it is in the same Git repository. On the other hand, some components (generally) can have very different change rates and reasons from other components. This can make rollbacks and bisecting difficult.

**Comment by clareliguori** [comment]
Yes, all the pipelines trigger on any commit to this repo.  If this wasn't a demo project, I would probably split the code into the following repos, largely following the top-level directories in this mono repo:
* static site
* chat-bot
* trivia-backend base image
* trivia-backend app
* canaries
* alarms
* pipelines

**Comment by alexpulver** [comment]
Thank you Clare!
