### ISSUE TITLE
Static site : Public S3 bucket

### ISSUE THREAD

**Issue by gmarchand** [aws-samples/aws-reinvent-2019-trivia-game#41]
Could it be possible to delete the public read access of the S3 bucket ? 
Could it be possible to use OIC with Cloudfront ?https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html#private-content-restricting-access-to-s3-overview ? 

ref : https://github.com/aws-samples/aws-reinvent-2019-trivia-game/blob/master/static-site/cdk/static-site.ts#L28

**Comment by clareliguori** [comment]
Thanks @gmarchand for letting me know about this method!
